######################################################################
# Automatically generated by qmake (2.01a) So. Aug 1 01:04:00 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Naub.h NaubScene.h NaubSim.h NaubView.h
SOURCES += main.cpp Naub.cpp NaubScene.cpp NaubSim.cpp NaubView.cpp
