######################################################################
# Automatically generated by qmake (2.01a) Sa. Jul 31 23:37:30 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Naub.h NaubScene.h NaubView.h
SOURCES += main.cpp Naub.cpp NaubScene.cpp NaubView.cpp
