#!/bin/sh

exists() { 
    command -v $1 > /dev/null && return 0
    return 1
}

python_version_2() { local version python2
    version=`python --version 2>&1`
    python2="Python 2*"
    case $version in $python2) return 0
    esac
    return 1
}

python2_cmd() {
    ( exists python2 && echo python2 ) || \
    ( exists python  && python_version_2 && echo python ) || \
    echo false
}

start() {
    `python2_cmd` "src/main.py" $@
}

start $@

