######################################################################
# Automatically generated by qmake (2.01a) Sa. Jul 31 00:53:51 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += analogclock.h
SOURCES += analogclock.cpp main.cpp
